// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ_zh5L8U6YRj1_k6LgYpbwynzpGbT5O0',
    appId: '1:309405115576:web:2e548075e2734ecf7b004d',
    messagingSenderId: '309405115576',
    projectId: 'sportz-333113',
    authDomain: 'sportz-333113.firebaseapp.com',
    storageBucket: 'sportz-333113.appspot.com',
    measurementId: 'G-XLKGG6P2PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsNjW0tQZ-5eKB2hpivhz2biZmkzIPytg',
    appId: '1:309405115576:android:aa8b7d70b48b1c947b004d',
    messagingSenderId: '309405115576',
    projectId: 'sportz-333113',
    storageBucket: 'sportz-333113.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV9GuWgPR9ADJoDty2V_XUnvNEX5O5I90',
    appId: '1:309405115576:ios:41de1cff8ecfa1207b004d',
    messagingSenderId: '309405115576',
    projectId: 'sportz-333113',
    storageBucket: 'sportz-333113.appspot.com',
    androidClientId: '309405115576-22ni5apmsairtkhg4io4poef4t1rt6j0.apps.googleusercontent.com',
    iosClientId: '309405115576-39jskshnen261cvkkqhg5vr1732reqed.apps.googleusercontent.com',
    iosBundleId: 'com.dev.app',
  );
}
